project_id = "ztyjbhzcvhaafjvkqmvv"

[auth]
  additional_redirect_urls = ["https://localhost:54321"]
  enable_email_confirmations = false
  enable_email_signup = true
  enable_phone_confirmations = false
  enable_phone_signup = false
  enable_signup = true
  enabled = true
  jwt_expiry = 3600
  site_url = "http://localhost:54321"
  [auth.external]
    enabled = false

[db]
  pooler_enabled = false

[functions]
  [functions.analyze-custom-case]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.autofix-case]
    verify_jwt = true
  [functions.generate-differential-diagnosis]
    verify_jwt = true
  [functions.generate-random-case]
    verify_jwt = true
  [functions.generate-session-feedback]
    verify_jwt = true
  [functions.populate-case-data]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.send-sus-reminder]
    verify_jwt = true
  [functions.treatment-hints]
    verify_jwt = true
  [functions.validate-case-acidbase]
    verify_jwt = true
