// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-clinical-cases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Conecte-se com sua conta VetBalance." }
    ],
    isError: true
  };
}

// src/lib/mcp/tools/list-clinical-cases.ts
var list_clinical_cases_default = defineTool({
  name: "list_clinical_cases",
  title: "Listar casos cl\xEDnicos",
  description: "Lista os casos cl\xEDnicos de desequil\xEDbrio \xE1cido-base dispon\xEDveis para o usu\xE1rio conectado (p\xFAblicos, pr\xF3prios e compartilhados).",
  inputSchema: {
    search: z.string().trim().optional().describe("Filtro opcional por nome do caso."),
    limit: z.number().int().optional().describe("N\xFAmero m\xE1ximo de casos retornados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("casos_clinicos").select("id, nome, especie, descricao, id_condicao_primaria, criado_em").order("id", { ascending: true }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (search) query = query.ilike("nome", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-clinical-case.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_clinical_case_default = defineTool2({
  name: "get_clinical_case",
  title: "Detalhar caso cl\xEDnico",
  description: "Retorna os detalhes de um caso cl\xEDnico: descri\xE7\xE3o, condi\xE7\xE3o prim\xE1ria e valores iniciais dos par\xE2metros fisiol\xF3gicos.",
  inputSchema: {
    case_id: z2.number().int().describe("ID num\xE9rico do caso cl\xEDnico.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: caso, error } = await supabase.from("casos_clinicos").select("id, nome, especie, descricao, id_condicao_primaria, criado_em").eq("id", case_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!caso) {
      return { content: [{ type: "text", text: "Caso n\xE3o encontrado ou sem acesso." }], isError: true };
    }
    const [{ data: condicao }, { data: valores }] = await Promise.all([
      caso.id_condicao_primaria ? supabase.from("condicoes").select("id, nome, descricao").eq("id", caso.id_condicao_primaria).maybeSingle() : Promise.resolve({ data: null }),
      supabase.from("valores_iniciais_caso").select("valor, parametros(nome, unidade, valor_minimo, valor_maximo)").eq("id_caso", case_id)
    ]);
    const result = { case: caso, condition: condicao ?? null, initial_values: valores ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-sessions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_sessions_default = defineTool3({
  name: "list_my_sessions",
  title: "Listar minhas simula\xE7\xF5es",
  description: "Lista as sess\xF5es de simula\xE7\xE3o do usu\xE1rio conectado, com status (won/lost/playing), dura\xE7\xE3o e caso associado.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Filtrar por status: won, lost ou playing."),
    limit: z3.number().int().optional().describe("N\xFAmero m\xE1ximo de sess\xF5es (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("simulation_sessions").select("id, nome, status, duracao_segundos, data_inicio, data_fim, case_id, casos_clinicos(nome, especie)").eq("user_id", ctx.getUserId()).order("data_inicio", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-session-report.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_session_report_default = defineTool4({
  name: "get_session_report",
  title: "Relat\xF3rio da simula\xE7\xE3o",
  description: "Retorna o relat\xF3rio de uma sess\xE3o de simula\xE7\xE3o do usu\xE1rio: dados da sess\xE3o, tratamentos aplicados e decis\xF5es registradas.",
  inputSchema: {
    session_id: z4.string().uuid().describe("ID (UUID) da sess\xE3o de simula\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: session, error } = await supabase.from("simulation_sessions").select("id, nome, status, duracao_segundos, data_inicio, data_fim, case_id, notas, casos_clinicos(nome, especie)").eq("id", session_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!session) {
      return { content: [{ type: "text", text: "Sess\xE3o n\xE3o encontrada." }], isError: true };
    }
    const [{ data: treatments }, { data: decisions }] = await Promise.all([
      supabase.from("session_treatments").select("timestamp_simulacao, tratamento_id, tratamentos(nome, tipo)").eq("session_id", session_id).order("timestamp_simulacao", { ascending: true }),
      supabase.from("session_decisions").select("*").eq("session_id", session_id).order("criado_em", { ascending: true }).limit(200)
    ]);
    const result = {
      session,
      treatments: treatments ?? [],
      decisions: decisions ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_my_progress_default = defineTool5({
  name: "get_my_progress",
  title: "Meu desempenho",
  description: "Resumo do desempenho do usu\xE1rio conectado: total de simula\xE7\xF5es, vit\xF3rias, derrotas, taxa de sucesso e conquistas (badges).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: sessions, error }, { data: badges }] = await Promise.all([
      supabase.from("simulation_sessions").select("status, duracao_segundos").eq("user_id", userId),
      supabase.from("user_badges").select("conquistado_em, badges(nome, tipo, descricao, icone)").eq("user_id", userId).order("conquistado_em", { ascending: false })
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const all = sessions ?? [];
    const wins = all.filter((s) => s.status === "won").length;
    const losses = all.filter((s) => s.status === "lost").length;
    const finished = wins + losses;
    const durations = all.map((s) => s.duracao_segundos).filter((d) => typeof d === "number");
    const result = {
      total_sessions: all.length,
      wins,
      losses,
      win_rate: finished > 0 ? Math.round(wins / finished * 100) : 0,
      average_duration_seconds: durations.length > 0 ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : null,
      badges: badges ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-treatments.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_treatments_default = defineTool6({
  name: "list_treatments",
  title: "Listar tratamentos",
  description: "Lista os tratamentos dispon\xEDveis no simulador VetBalance, com tipo e descri\xE7\xE3o.",
  inputSchema: {
    tipo: z5.string().trim().optional().describe("Filtrar por tipo de tratamento.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tipo }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tratamentos").select("id, nome, tipo, descricao").order("nome");
    if (tipo) query = query.eq("tipo", tipo);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { treatments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ztyjbhzcvhaafjvkqmvv";
var mcp_default = defineMcp({
  name: "vetbalance",
  title: "vetbalance",
  version: "0.1.0",
  instructions: "Ferramentas do VetBalance, simulador gamificado de dist\xFArbios \xE1cido-b\xE1sicos em Medicina Veterin\xE1ria. Use `list_clinical_cases` e `get_clinical_case` para explorar casos cl\xEDnicos, `list_treatments` para os tratamentos dispon\xEDveis, e `list_my_sessions`, `get_session_report` e `get_my_progress` para o hist\xF3rico e desempenho do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clinical_cases_default,
    get_clinical_case_default,
    list_treatments_default,
    list_my_sessions_default,
    get_session_report_default,
    get_my_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
